@ECHO OFF
ng g c --skipTests category/angry & ^
ng g c --skipTests category/bad-mood & ^
ng g c --skipTests category/bear & ^
ng g c --skipTests category/beg & ^
ng g c --skipTests category/blush & ^
ng g c --skipTests category/cat & ^
ng g c --skipTests category/confused & ^
ng g c --skipTests category/cry & ^
ng g c --skipTests category/cute & ^
ng g c --skipTests category/dance & ^
ng g c --skipTests category/depressed & ^
ng g c --skipTests category/devil & ^
ng g c --skipTests category/disappointed & ^
ng g c --skipTests category/drool & ^
ng g c --skipTests category/eat & ^
ng g c --skipTests category/evil & ^
ng g c --skipTests category/excited & ^
ng g c --skipTests category/fall-down & ^
ng g c --skipTests category/feces & ^
ng g c --skipTests category/feminine & ^
ng g c --skipTests category/flip-table & ^
ng g c --skipTests category/flower & ^
ng g c --skipTests category/funny & ^
ng g c --skipTests category/glasses & ^
ng g c --skipTests category/grin & ^
ng g c --skipTests category/gross & ^
ng g c --skipTests category/happy & ^
ng g c --skipTests category/heart & ^
ng g c --skipTests category/hello & ^
ng g c --skipTests category/helpless & ^
ng g c --skipTests category/hide & ^
ng g c --skipTests category/hug & ^
ng g c --skipTests category/kiss & ^
ng g c --skipTests category/laugh & ^
ng g c --skipTests category/lenny-face & ^
ng g c --skipTests category/love & ^
ng g c --skipTests category/make-up-my-mind & ^
ng g c --skipTests category/middle-finger & ^
ng g c --skipTests category/monkey & ^
ng g c --skipTests category/music & ^
ng g c --skipTests category/nervous & ^
ng g c --skipTests category/peace-sign & ^
ng g c --skipTests category/proud & ^
ng g c --skipTests category/punch & ^
ng g c --skipTests category/rabbit & ^
ng g c --skipTests category/roger-that & ^
ng g c --skipTests category/roll-over & ^
ng g c --skipTests category/run & ^
ng g c --skipTests category/sad & ^
ng g c --skipTests category/salute & ^
ng g c --skipTests category/scared & ^
ng g c --skipTests category/sheep & ^
ng g c --skipTests category/shocked & ^
ng g c --skipTests category/shrug & ^
ng g c --skipTests category/shy & ^
ng g c --skipTests category/sleep & ^
ng g c --skipTests category/smile & ^
ng g c --skipTests category/sparkle & ^
ng g c --skipTests category/spin & ^
ng g c --skipTests category/surprised & ^
ng g c --skipTests category/sweat & ^
ng g c --skipTests category/take-a-bow & ^
ng g c --skipTests category/thats-it & ^
ng g c --skipTests category/thumbs-up & ^
ng g c --skipTests category/tremble & ^
ng g c --skipTests category/try-my-best & ^
ng g c --skipTests category/unicode & ^
ng g c --skipTests category/upset & ^
ng g c --skipTests category/vomit & ^
ng g c --skipTests category/weird & ^
ng g c --skipTests category/wink
PAUSE
